TITLE="Beej's Guide to Network Concepts"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v1.0.23, Copyright © October 1, 2024"

GUIDE_ID=bgnet0
BGBSPD_BUILD_DIR?=../../bgbspd
WEB_IMAGES=$(wildcard *.svg *.png)

include $(BGBSPD_BUILD_DIR)/source.make

